### PR TITLE
esp, tx, add radiomaster RP4TD as tx for SiK

### PR DESCRIPTION
**Pull request by olliw42**
title says it

I like to add the radiomaster RP4TD receiver as tx module to the code base. We do have a lack of transmitters, and thx to it's 2nd uart port which can be used as CLI it is quite well suited as SiK replacemement.

@jlpoltrack @tmcadam

### CODE REVIEW

**Comment by tmcadam** [comment]
I think this a good step. I don't have the RP4D to test with. My RM Bandit 900 TX has an additional uart broken out, maybe I can create a simple hal for this to test with (ignoring the oled and fancy leds). Two of these modules would give you a serial link with significant range! 

image

**Comment by olliw42** [comment]
did you guys come to a conclusion/decission?

**Comment by tmcadam** [comment]
I haven't had a chance to test this. I am happy with the concept and have looked through the code.

**Comment by jlpoltrack** [comment]
Fine with me to merge as well, then can work on the Docs.  @tmcadam Do you want to hit the button?

**Comment by olliw42** [comment]
MANY THX guys !!

**Pull request merged**
