### PR TITLE
Esp interrupt cleanup

### PR DESCRIPTION
**Pull request by jlpoltrack**
Rationale: ESP32 doesn't like noInterrupts / Interrupts functions.  

This removes them from the ESP8266 code, tested with Generic 900.

- Removing from rxclock had no impact.
- In order for EEPROM write to succeed, DIO interrupt needs to be disabled.  Created a new function in the SX127x and SX128x drivers called 'deInit' which does this.

If this makes sense, will also need to update all of the Hals to detach the DIO interrupt.

### CODE REVIEW

**Comment by olliw42** [comment]
I think we had this discussion, at least it looks to me we did ... and it totally does not make sense to me. Not protecting a critical block is just not ok. Frankly, to me it looks like we just don't know how to do it correctly.

**Comment by olliw42** [comment]
also I think this shouldn't go into main but a esp dev branch. IMHO we shouldn't fumble with main until we see how it all unfolds and pieces together for esp32

**Comment by jlpoltrack** [comment]
> also I think this shouldn't go into main but a esp dev branch. IMHO we shouldn't fumble with main until we see how it all unfolds and pieces together for esp32

Good point, I will close this PR.

I understand your point on the critical RXClock piece.  Are you strongly against the DeInit concept?

**Comment by olliw42** [comment]
> Are you strongly against the DeInit concept?

not neccessarily, I just don't see it should be needed

I guess I will do a search in the elrs code base for attachInterrupt and deattach, I feel we are missing something

**Pull request closed without merging**
