### PR TITLE
esp, esp lib improvements, comments&tidy

### PR DESCRIPTION
**Pull request by olliw42**
some few additions/changes to the esp lib files, and a comment
this brings over some stuff from the owpr-esp-tx branch
- less IRAM static inline
- gpio handling for pin >= 32
- some comments nfc

should be a light review :)

### CODE REVIEW

**Comment by jlpoltrack** [comment]
Will test more later, but just a quick IRAM check -no change: 

SuperD, current main:

image

SuperD, this branch:

image

I believe the reason for this is because the configs in platformio.ini are taking precedence.

**Comment by olliw42** [comment]
very cool, thx!
just did another small commit to change y to 1 in the platformio.ini ... should have been changed to 1 already, not sure where this was scrambled up...

**Comment by tmcadam** [comment]
Looks fine to me. I can test on hardware tonight if you would like another hardware test? If not I am happy to approve as is.

**Comment by olliw42** [comment]
you guys could merge?

**Comment by jlpoltrack** [comment]
Seems like everyone is good - will merge.

**Pull request merged**
