### PR TITLE
rx, transmit diversity

### PR DESCRIPTION
**Pull request by jlpoltrack**
Works on the bench - but not sure if I'm missing anything here :)

### CODE REVIEW

**Comment by olliw42** [comment]
ah, very interesting. I just happen to have started to continue my work on this, albeit I'm focusing for the moment on the tx side. I've just made me a logger to log the complete real-time transmitter stats data, to work out a scheme.

I can't claim for sure, but I think this is too simplistic. Especially I'm concerned about what's happening near connection loss (i.e. in the presence of substantial frame losses) as well as when disconnected. I also somehow feel that there should be some time constant, e.g. from some filtering, as well as some hysteresis. The point is that the momentary interference or loss of packet on a frequency does not typically mean that the over-the-air channel properties have changed, e.g. becasue the vehicle has changed it position oin space. So, the simplistic scheme may actually most of the time jump to the bad antenna. Just my thoughts on the matter.

BTW, I'm going to do my experiments for tezh tx transmit diversity with a 2dBi omni antenna on one port and a 7 dBi directional antenna on the other port. Would be a cool general configuration, I guess. (doesn't make sense on rx side, of course)

**Comment by jlpoltrack** [comment]
Fair enough - will be interesting to see your findings.  I will try to do at least 1 flight with this basic implementation and share what I see.

Hardware wise - I seem to be moving towards single antenna (directional, e.g. moxon) Tx and diversity on the Rx side.

**Comment by olliw42** [comment]
any technical reason for closing which would be worth knowing?

**Comment by jlpoltrack** [comment]
No technical reason, just tidying :)

**Comment by olliw42** [comment]
ha, ok, thx!

you have seen this PR https://github.com/olliw42/mLRS/pull/108 ?

**Pull request closed without merging**
