### PR TITLE
dev-esp-iflight-2.4

### PR DESCRIPTION
**Pull request by jlpoltrack**
- Adds two targets: iFlight 250 mW True Diversity 2.4G, iFlight 500 mW 2.4G
- Cleanup of platformio.ini to align with esp-hal and esp-device_conf

### CODE REVIEW

**Comment by jlpoltrack** [comment]
> you did confirm the power levels yourself, or Joost did?

Power levels are unconfirmed but use ELRS values.  I'm pretty sure these use the same RF Frontend as the E28-2G4M27S based on what I see in the ELRS repo.

**Comment by olliw42** [comment]
in discord you presented a power level chart, did show consistently 9 dB too much. 
so, this here is correcting for the 9 dB, right?
any reason not to double check (from the chart I conclude you have power meter :)) 

anyway, I'm just nitpicking, as always. If you guys want to merge you have my lgtm :):):)

please do not forget to change the commit title to something starting with "esp, ....."

**Comment by jlpoltrack** [comment]
Well the challenge is that I don't have this hardware (and am also not sure if Joost has power meter) :)

**Comment by olliw42** [comment]
ah ... so the power level chart was based on what you know, not what was actually measured ...

I guess we could ask Joost to retry with the new hal firmware, and he when at least should not see issues in the highest pwoer level, right?

**Comment by olliw42** [comment]
if I read discord correctly, it was just confrimed to be all good

from my side hence: pl go ahead with merging. lgtm

MANY THX!!!!

**Pull request merged**
