### PR TITLE
Replace commented out broken code with reason

### PR DESCRIPTION
**Pull request by brad112358**
Sorry.  I didn't mean to leave this comment in.  Replace it with a more meaningful comment.

### CODE REVIEW

**Comment by olliw42** [comment]
I have seen that but was okay since I'll push some changes in a minute
so I close without merge as it would screw up my branch I'm preparing :)
THX anyway!!!

**Comment by brad112358** [comment]
OK.  Thanks!

**Comment by brad112358** [comment]
BTW, I do have another PR I am preparing which speeds up parameter download and makes it more reliable.

**Comment by olliw42** [comment]
interesting
I am actually also working on such a thing using a newly introduced mavlink message to pack the params
not yet finished, but I'm afraid we may overlap and your changes may collide
the idea is to collect param messages on the rx side and compress them into a PARAM_VALUE_ARRAY message and send this to the tx instead 8screws up seq no, but hey...). should increase it by a factor of >3.
This https://github.com/mavlink/mavlink/issues/1918 is related.
concerning reliability I think anything should go ontop of this resend thing done, still had no time to work it out, sadly (I'm lately very busy with STorM32)

**Comment by brad112358** [comment]
This is very interesting.  I haven't yet taken the time required to read the entire discussion you referenced.  I will need to look at it again to understand why your proposal is better than making FTP work correctly on low bandwidth links.  I wasn't quite ready, but I think I'll issue a PR for the code I have now just so you can see what I've been working on and to give us a place to discuss it.

**Comment by olliw42** [comment]
yes, pl, PR it, I'm curious
I just wanted to indicate that I might maybe not immediately jump onto it, due to this alternative approach :).
The suggestion I've made didn't fly and won't come to live. Hence my effort now within mLRS. Fundamentally it is not "better" than FTP in terms of download speed, the issue is concept-wise and number of protocols  wise ... and I mean, all GCSes and ArduPilot still struggle to get it right, even after several years... 
In ArduPilot v4.3.3 ftp should work better now, iff (if and only if) you set the baudrate to a correspondingly low value, which we (I) don't want at all. Still no txbuf handling yet. Furthermore, ArduPilot started now to send even metadata (this default thing which yopur PR corrected for), which makes the download unneccessarily large = slower (it is really sad that they again screw things up, and don't use the comp_info mechanism, which is exactly for that purpose)(they just never will learn it, and I by now have the theory, well supported by evidence, that they play ill by purpose, to just not do what mavlink comes up with, their brains just seem to stop working properly on mavlink matter)

**Pull request closed without merging**
