### PR TITLE
high refresh crsf tweak

### PR DESCRIPTION
**Pull request by jlpoltrack**
Have been doing some testing with 100, 111 and 125 Hz modes for FLRC and this change was needed for all of them.

### CODE REVIEW

**Comment by olliw42** [comment]
@jlpoltrack wouldn't 10ms/100Hz be ok with just slowing down by a factor 2 (i.e. with cnt >1)?
I wonder if it would be worth to add two cases, one for rate_ms < 20 ms which slows by factor of 2, and one with < 10ms which slows by a factor of 3, like now.
Any insights/thoughts?

**Comment by jlpoltrack** [comment]
I don't notice any difference on the radio and since it is wanted to only have 1 FLRC mode, I think just having one condition makes more sense.

**Comment by olliw42** [comment]
thx
couldn't it make sense to set the limit more conversatively, I mean, the next is at 20 ms, and we probably want to start slowing down sonner than at 10 ms (at let's say 15 ms there already wouldn't be space for telemrtry frames). So maybe we should change to rate_ms <= 19 or so ...

**Comment by jlpoltrack** [comment]
> thx couldn't it make sense to set the limit more conversatively, I mean, the next is at 20 ms, and we probably want to start slowing down sonner than at 10 ms (at let's say 15 ms there already wouldn't be space for telemrtry frames). So maybe we should change to rate_ms <= 19 or so ...

Yea, this makes sense to me.  Will update

**Comment by olliw42** [comment]
MANY THX!!

**Pull request merged**
