### PR TITLE
Don't assume the current directory is in the execution path

### PR DESCRIPTION
**Pull request by brad112358**
This should fix the trouble some people have with run_setup.py on Linux
I have not checked that this still works on Windows, but I think it should.

### CODE REVIEW

**Comment by olliw42** [comment]
else one might need something like 
```
    if os.name == 'nt': # the os is Windows
        os.system('fmav_generate_c_library.py')
    else:
        os.system('./fmav_generate_c_library.py')
```

I guess

**Comment by brad112358** [comment]
> @brad112358 many thanks! it unfortunately is not working on Win also... would os.system(os.path.join('.','fmav_generate_c_library.py')) work on linux?
Crap.  I had read that Python on windows did the translation from / to \  But I guess not in this case.
Yes, I think that would work.  I'll test it...

**Comment by brad112358** [comment]
Yes, your os.path.join suggestion works on Linux.   I'm sure it works on Windows too (and not just because you probably already tested it).  :)

**Comment by olliw42** [comment]
yes, I did test the suggested change with join ... great to hear it also works on linux
so, will merge
THANKS!!!

**Pull request merged**
